version: '3'

services:
  client:
    build:
      context: .
    ports:
      - '80:80'
    volumes:
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - book_server
    container_name: web_server
