name: production docker build and push

on:
  push:
    branches:
      - production
jobs:
  docker_build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
